version: "3.2"

services:

  console:
    image: kendokan/console:latest
    build: /mnt/system0/docker/build/console
    hostname: console
    volumes:
      - ~/.ssh:/home/core/.ssh
      - ~/.git:/home/core/.git
      - ~/.gitconfig:/home/core/.gitconfig
      - /mnt:/mnt
      - /mnt/system0/docker:/home/core/docker
      - /var/run/docker.sock:/var/run/docker.sock

